### ISSUE TITLE
[S2 - PBI11] Membuat halaman artikel

### ISSUE THREAD

**Issue by Diyasyaklunabaihaqi** [SI-RPL-2023/SI4402_C_DOBU#10]

**Comment by mhaikalap** [comment]
[S2 - PBI11] Membuat halaman artikel
Sebagai user, saya ingin dapat melihat artikel mengenai buku dan manfaat membaca

Size 2 Hari

Activity Diagram halaman artikel :


![Image](https://user-images.githubusercontent.com/115625563/235400909-4d8ec026-6292-4d2c-bfa2-d1bfc5844464.png)

Halaman artikel adalah halaman yang menampilkan beberapa informasi mengenai seputaran donasi buku, seperti info dll.


![Image](https://user-images.githubusercontent.com/115625563/235401992-a1cac59e-8959-4f44-9448-f06daa9947b3.png)

SS Tampilan :



![Image](https://github.com/SI-RPL-2023/SI4402_C_DOBU/assets/115625563/8c65c799-54c6-4b1f-b163-79ac814ccd05)



SS CRUD :


![Image](https://user-images.githubusercontent.com/115625563/235402324-c01cfd52-a007-4433-b6d6-f10fc4e66482.png)
