### ISSUE TITLE
[S2 - PBI12] Membuat halaman FAQ

### ISSUE THREAD

**Issue by Diyasyaklunabaihaqi** [SI-RPL-2023/SI4402_C_DOBU#11]

**Comment by arthurr15** [comment]
S2-PBI12 Sebagai user, saya ingin dapat bertanya jika saya mengalami kesulitan

![Image](https://user-images.githubusercontent.com/115915139/231525654-3413009d-67dc-4478-955f-241681f18d4a.png)



![Image](https://user-images.githubusercontent.com/115915139/231525783-fa58c699-5fdb-402e-bfbf-5ba0cc06c23d.png)



![Image](https://user-images.githubusercontent.com/115634735/235402224-6f2dcfcd-10ab-422b-a667-6d6ab64ac7ff.png)
