### ISSUE TITLE
[S2 - PBI13] Membuat halaman event

### ISSUE THREAD

**Issue by Diyasyaklunabaihaqi** [SI-RPL-2023/SI4402_C_DOBU#12]

**Comment by FandiSetyoso** [comment]
S2.PBI13: Fitur Event
Sebagai user, saya ingin mengetahui acara apa saja yang akan berlangsung 

Size: 3 hari

(BPMN)


![Image](https://user-images.githubusercontent.com/115622813/230275736-57233584-1dd6-4aff-9bf5-16647a9b3815.png)


(Activity diagram)


![Image](https://user-images.githubusercontent.com/115622813/230275793-7b7714d3-52cd-46b3-89be-29fab0490dce.png)

SS Tampilan halaman yang sudah jadi



![Image](https://github.com/SI-RPL-2023/SI4402_C_DOBU/assets/115915139/e5a7a974-4d87-4e10-945d-aca0ead443a8)
