### ISSUE TITLE
[S1 - PBI8] Membuat halaman logout

### ISSUE THREAD

**Issue by Diyasyaklunabaihaqi** [SI-RPL-2023/SI4402_C_DOBU#13]

**Comment by mhaikalap** [comment]
[S1 - PBI8] Membuat halaman logout #13
Sebagai user, saya ingin dapat melakukan logout dari web DOBU

Size 2 hari

Activity Diagram Logout :
![Image](https://user-images.githubusercontent.com/115625563/231527782-9110baee-365b-4889-b8b3-1ebf1de52d4b.png)

SS tampilan halaman logout yang sudah jadi
![image](https://user-images.githubusercontent.com/115605407/232275297-25fc5368-05dd-40b4-bce3-d3935990dbd6.png)
