### ISSUE TITLE
[S3 - PBI18] Membuat halaman kelola donasi buku admin	

### ISSUE THREAD

**Issue by Diyasyaklunabaihaqi** [SI-RPL-2023/SI4402_C_DOBU#15]
S3.PBI18: Fitur Kelola halaman kelola donasi buku admin
Sebagai admin, saya ingin melihat kesesuaian data diri saya pada halaman profil

Size: 2 Hari

SS CRUD

![Image](https://github.com/SI-RPL-2023/SI4402_C_DOBU/assets/115605407/7f9f6117-8e94-4977-9a48-c26dfb56fbf9)

SS Halaman

![Image](https://github.com/SI-RPL-2023/SI4402_C_DOBU/assets/115634735/85d2729c-4430-4cf9-8fd0-910db6b6b586)

**Comment by arthurr15** [comment]
Halaman pembuatan donasi buku admin adalah sebuah fitur dimana admin bisa membuka dan melihat data perihal user yang melakukan donasi
