### ISSUE TITLE
[S3 - PBI20] Membuat halaman kelola artikel admin

### ISSUE THREAD

**Issue by Diyasyaklunabaihaqi** [SI-RPL-2023/SI4402_C_DOBU#17]

**Comment by FandiSetyoso** [comment]
[S3 - PBI20] Membuat halaman kelola artikel admin #17
Membuat halaman untuk mengelola artikel yang dilakukan oleh admin

Size 2 hari

Halaman mengelola artikel adalah halaman yang digunakan admin untuk mengelola artikel yang nantinya akan ditampilkan di dalam menu artikel user. Admin dapat menambah, mengedit, dan menghapus artikel.

**Comment by FandiSetyoso** [comment]
Berikut CRUD dari halaman kelola artikel admin


![Image](https://github.com/SI-RPL-2023/SI4402_C_DOBU/assets/115622813/aac12f72-1f79-4ffa-9451-2b516bdef298)

Screenshot halaman kelola artikel


![Image](https://github.com/SI-RPL-2023/SI4402_C_DOBU/assets/115622813/f420240e-91a7-4bb2-8acb-3a704986ceac)
