### ISSUE TITLE
[S3 - PBI22] Membuat halaman kelola event admin	

### ISSUE THREAD

**Issue by Diyasyaklunabaihaqi** [SI-RPL-2023/SI4402_C_DOBU#19]
S3.PBI22: Fitur halaman kelola event admin
Saya sebagai admin bisa melakukan penambahan,edit,dan menghapus dari Event yang telah dibuat untuk bisa ditampilin di tampilan user

Size: 2 Hari

SS Proses Binis Kelola Event Admin

![Image](https://github.com/SI-RPL-2023/SI4402_C_DOBU/assets/115605407/950ebfdc-0be6-4d5e-ad34-d74611ac7aa8)

SS CRUD

![Image](https://github.com/SI-RPL-2023/SI4402_C_DOBU/assets/115605407/1c74faa7-ee0a-4f93-88e2-aef0ec308d85)

SS Tampilan Halaman Kelola Event Admin

![Image](https://github.com/SI-RPL-2023/SI4402_C_DOBU/assets/115605407/c808240c-783a-4281-b201-0a8ab416dcc3)

**Comment by arthurr15** [comment]
Halaman event admin adalah halaman dimana admin bisa melihat dan mengelola event
