### ISSUE TITLE
[S3 - PBI23] Membuat halaman kelola bank buku admin

### ISSUE THREAD

**Issue by Diyasyaklunabaihaqi** [SI-RPL-2023/SI4402_C_DOBU#20]

**Comment by mhaikalap** [comment]
S3-PBI23 : Fitur Membuat halaman kelola bank buku admin
Sebagai admin, saya ingin dapat mengelola bank buku yang ada.

Size : 2 Hari

CRUD :
![Image](https://github.com/SI-RPL-2023/SI4402_C_DOBU/assets/115625563/94f92aae-4c2f-4f6a-aac6-84dc965fe33e)

Activity Diagram :


![Image](https://github.com/SI-RPL-2023/SI4402_C_DOBU/assets/115625563/afaec60b-0839-4acc-bab0-ed1d3c567588)

SS Tampilan :



![Image](https://github.com/SI-RPL-2023/SI4402_C_DOBU/assets/115625563/cb3b8cd6-b7e0-437d-81af-f18fd7f6802d)
