### ISSUE TITLE
[S2 - PBI14] Membuat halaman profile admin

### ISSUE THREAD

**Issue by Diyasyaklunabaihaqi** [SI-RPL-2023/SI4402_C_DOBU#22]

**Comment by FandiSetyoso** [comment]
[[S2 - PBI15] Membuat halaman profile admin
Sebagai admin, saya ingin melihat kesesuaian data diri saya pada halaman profil

Size 2 hari

**Comment by FandiSetyoso** [comment]
Activity diagram profile
![Image](https://user-images.githubusercontent.com/115622813/235399990-f46113ac-1196-4b79-89fb-cc47a99e0bd2.png)

Screenshot halaman profile admin
![Image](https://github.com/SI-RPL-2023/SI4402_C_DOBU/assets/115622813/6ca38cbc-0140-4b18-a4e5-6080ec29cd3d)
