### ISSUE TITLE
[S2 - PBI17] Membuat halaman logout admin

### ISSUE THREAD

**Issue by Diyasyaklunabaihaqi** [SI-RPL-2023/SI4402_C_DOBU#24]

**Comment by mhaikalap** [comment]
[S2 - PBI11] Membuat halaman logout admin
Sebagai admin, saya ingin dapat melakukan logout dari web DOBU

Size 2 Hari

Activity Diagram halaman logout admin :


![Image](https://user-images.githubusercontent.com/115625563/235403545-b2335b02-2310-491c-af12-52276503084a.png)

SS Tampilan :



![Image](https://github.com/SI-RPL-2023/SI4402_C_DOBU/assets/115625563/c23869b6-3b96-4b83-bcb8-94f5a18484ba)
