### ISSUE TITLE
[S1 - PBI4] Membuat halaman Dasboard

### ISSUE THREAD

**Issue by Diyasyaklunabaihaqi** [SI-RPL-2023/SI4402_C_DOBU#4]

**Comment by Diyasyaklunabaihaqi** [comment]
[S1 - PBI4] Membuat halaman Dasboard #4
Sebagai user, saya ingin bisa melihat fitur dan layanan yang tersedia

Size 2 Hari

MOCKUP DASHBOARD USER
![Image](https://user-images.githubusercontent.com/115605407/227708424-24194ef8-e6bc-4c0b-81a4-9efcbfc0d041.png)

SS tampilan halaman yang sudah jadi
![image](https://user-images.githubusercontent.com/115605407/232274450-97dc6495-6f13-419b-99d4-7f9299461e56.png)

**Comment by FandiSetyoso** [comment]
![Image](https://user-images.githubusercontent.com/115622813/232235150-0a82ee24-488f-4689-b5b8-82153c4102d9.png)

Berikut merupakan tampilan halaman dashboard yg telah selesai. Pengerjaan halaman dashboard berikut memakan waktu selama 7 hari pengerjaan. halaman dashboard yang telah dibuat juga telah sesuai dengan mockup yg ditentukan.
