### ISSUE TITLE
[S1 - PBI5] Membuat halaman profile

### ISSUE THREAD

**Issue by Diyasyaklunabaihaqi** [SI-RPL-2023/SI4402_C_DOBU#5]

**Comment by Diyasyaklunabaihaqi** [comment]
[S1 - PBI5] Membuat halaman profile #5
Sebagai user dan admin saya ingin melihat kesesuaian data diri saya pada halaman profil

Size 2 Hari

Activity Diagram Melihat Profile User
![Image](https://user-images.githubusercontent.com/115605407/227708531-e46482f2-dca1-4fdb-b3db-976fbb9a545d.png)

SS tampilan Halaman profile 
Berikut merupakan tampilan dari halaman profile dari user yang telah selesai. Pengerjaan halaman ini memakan waktu 5 hari pengerjaan. dan pengerjaan dari halaman profile ini sudah disesuaikan dengan alur activity diagram yang sudah kita buat.
![image](https://user-images.githubusercontent.com/115605407/232274651-85ef38c0-a02d-42a3-9546-3b9966fc86a0.png)

**Comment by arthurr15** [comment]
Membuat Halaman profile user



![Image](https://user-images.githubusercontent.com/115915139/232254091-9a2e6cca-7cb1-41ae-84f5-a526c380a88a.png)

Berikut merupakan tampilan dari halaman profile dari user yang telah selesai. Pengerjaan halaman ini memakan waktu 5 hari pengerjaan. dan pengerjaan dari halaman profile ini sudah disesuaikan dengan alur activity diagram yang sudah kita buat.
