### ISSUE TITLE
[S1 - PBI7] Membuat halaman lokasi

### ISSUE THREAD

**Issue by Diyasyaklunabaihaqi** [SI-RPL-2023/SI4402_C_DOBU#7]

**Comment by Diyasyaklunabaihaqi** [comment]
[S1 - PBI7] Membuat halaman lokasi #7
Sebagai user, saya ingin dapat melihat informasi lokasi penyerahan buku

Size 2 hari

Activity Diagram Melihat Lokasi Gudang DOBU  user
![Image](https://user-images.githubusercontent.com/115605407/227708709-672bc816-fd51-45d8-b234-30cf82445e6d.png)

SS CRUD yang ada di phpmyadmin
![image](https://user-images.githubusercontent.com/115605407/232275124-2e1b5024-4740-4fe1-a861-6749c5ce0594.png)

SS tampilan halaman lokasi yang sudah jadi 
![image](https://user-images.githubusercontent.com/115605407/232275168-83340b3d-c97f-4685-a853-0054df4200c9.png)

**Comment by arthurr15** [comment]
Pembuatan Halaman Lokasi 



![Image](https://user-images.githubusercontent.com/115915139/232254222-a0495c12-80dd-4f27-9e0f-934293598c99.png)

Berikut merupakan tampilan dan hasil pengerjaan dari halaman Lokasi yang telah selesai. Halaman lokasi memakan waktu 10 hari pengerjaan, dan halaman ini sudah kita sesuaikan dengan alur dari activity diagram yang telah kita buat. Halaman lokasi yang kami buat ini sudah menggunakan back end untuk mengaplikasikan map atau lokasi dari DOBU.
