### ISSUE TITLE
[S2 - PBI9] Membuat halaman donasi buku

### ISSUE THREAD

**Issue by Diyasyaklunabaihaqi** [SI-RPL-2023/SI4402_C_DOBU#8]

**Comment by FandiSetyoso** [comment]
[S2 - PBI9] Membuat halaman donasi buku #8
Sebagai user, saya ingin dapat melakukan donasi buku

Size 2 Hari

Activity Diagram donasi buku user
![Image](https://user-images.githubusercontent.com/115622813/230275483-3b5a1474-fc53-4355-8b37-9224292cc671.png)


Halaman donasi buku adalah halaman yang menampilkan informasi tentang 
donasi dan cara menjadi donatur. Halaman donasi buku menampilkan 
informasi seperti form pengajuan donasi yang akan diisi.
![Image](https://user-images.githubusercontent.com/115622813/230275456-1ba83545-9a18-4137-bd0c-2ffd07c46fcd.png)

Screenshot halaman donasi buku


![Image](https://github.com/SI-RPL-2023/SI4402_C_DOBU/assets/115622813/bb8c2667-b45c-4522-b6ae-40da5089cc5b)
