### ISSUE TITLE
[S2 - PBI10] Membuat halaman request buku

### ISSUE THREAD

**Issue by Diyasyaklunabaihaqi** [SI-RPL-2023/SI4402_C_DOBU#9]

**Comment by mhaikalap** [comment]
[S2 - PBI9] Membuat halaman request buku user
saya sebagai user ingin melakukan request buku

Size 2 hari 

Activity Diagram Request Buku :
![Image](https://user-images.githubusercontent.com/115625563/231526801-81e31c71-cb0c-4f77-b1f5-a2b4622923f3.png)

Probis Request Buku
![Image](https://user-images.githubusercontent.com/115625563/231527190-9619f2a3-bfc5-4668-948f-dfa2601ee5d9.png)

SS CRUD phpmyadmin


![Image](https://user-images.githubusercontent.com/115605407/235403825-e124d253-b64b-4b57-9af0-3414621f5fcd.png)

SS Tampilan Fitur Request Buku



![Image](https://github.com/SI-RPL-2023/SI4402_C_DOBU/assets/115605407/705b5047-7cdd-4bfc-9949-13eb038e81b5)
